spring.application.name=salaryservice
# URL kết nối (thay đổi localhost, port và databaseName tương ứng)
server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=salaryservice;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Dialect cho SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Tự động tạo/cập nhật bảng (chỉ dùng khi phát triển)
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# In chi tiết các bước kiểm tra bảo mật
logging.level.org.springframework.security=DEBUGQA